force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Basic_Salary__c.field-meta.xml
<CustomField>
    <fullName>Basic_Salary__c</fullName>
    <label>Basic_Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Emp_Location__c.field-meta.xml
<CustomField>
    <fullName>Emp_Location__c</fullName>
    <label>Emp Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kadapa</fullName>
            </value>
            <value>
                <fullName>Nellore</fullName>
            </value>
            <value>
                <fullName>Guntur</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFDC-GitHub/force-app/main/default/classes/searchEmployeeClass.cls
public with sharing class searchEmployeeClass   {

    @AuraEnabled(Cacheable = true)
    public static list<Employee__c> retriveEmp(String strEmpName, string strLocation) {
        strEmpName = '%' + strEmpName + '%';
        strLocation = '%' + strLocation + '%';
        list<Employee__c> lstAccs = [SELECT  Id, Name, Basic_Salary__c, Emp_Location__c From Employee__c 
                                    WHERE Name LIKE :strEmpName OR Emp_Location__c LIKE :strLocation];

        if(lstAccs.isEmpty()) {
            throw new AuraHandledException('No Record Found..');
        }
        return lstAccs; 
    }
}