force-app/main/default/objects/caseRecordEdit__mdt/caseRecordEdit__mdt.object-meta.xml
<CustomObject>
    <label>caseRecordEdit</label>
    <pluralLabel>caseRecordEdits</pluralLabel>
</CustomObject>

force-app/main/default/objects/caseRecordEdit__mdt/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <label>Field_Label</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/caseRecordEdit__mdt/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field_Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/caseComponentClass2.cls
public class caseComponentClass2 {
@Auraenabled
    Public static List<string> fieldApis(){
        List<string> fieldNameSet = new List<string>();
        
        for(caseRecordEdit__mdt steobj: [select id,Field_Label__c,Field_Name__c from caseRecordEdit__mdt]){
            fieldNameSet.add(steobj.Field_Name__c);
        }
                    return fieldNameSet;
    }
    @Auraenabled
    Public static case saveRecord(Case RecordDetail){
        insert RecordDetail;
        return RecordDetail;
        
        
    }
    
}