force-app/main/default/objects/Faculty__c/Faculty__c.object-meta.xml
<CustomObject>
    <label>Faculty</label>
    <nameField>
        <label>Faculty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faculties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Faculty__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <label>Faculty</label>
    <referenceTo>Faculty__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/School_Name__c.field-meta.xml
<CustomField>
    <fullName>School_Name__c</fullName>
    <label>School Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Student_Roll_No__c.field-meta.xml
<CustomField>
    <fullName>Student_Roll_No__c</fullName>
    <label>Student Roll No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFDC-GitHub/force-app/main/default/classes/AccountCreationbyUsingProperties.cls
public class AccountCreationbyUsingProperties 
{
    public String accName{set;get;}
    public String acctype{set;get;}
    
  /*  public string stuname{set;get;}
    public string fname{set;get;}
    public string addr{set;get;}
    public string faculty{set;get;}
    public string mname{set;get;}
    public string schoolname{set;get;}
    public string gender{set;get;}
    public string email{set;get;}
    public integer phone{set;get;}
    public integer roleno{set;get;}   */
    	
    	
    public pageReference saveAccount()
    {
        Account accobj = new Account();
      accobj.Name = accName;
        accobj.Type = accType;
        insert accobj;
       return new pageReference('/'+accobj.Id);
        
    
   /*     Student__c stu = new Student__c();
        stu.Name = stuname;
        stu.Father_Name__c = fname;
        stu.Address__c = addr;
        stu.Email__c = email;
        stu.Faculty__c = faculty;
        stu.Mother_Name__c = mname;
       // stu.Phone_Number__c = phone;
        stu.Student_Roll_No__c = roleNo;
        stu.School_Name__c = schoolname;
        stu.Gender__c = gender;
        insert stu;
        return new pageReference('/'+stu.Id);   */
    }
}