force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Department_Location__c.field-meta.xml
<CustomField>
    <fullName>Department_Location__c</fullName>
    <label>Department_Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kadapa</fullName>
            </value>
            <value>
                <fullName>Nellore</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Warangal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Department__c/fields/Establish_Date__c.field-meta.xml
<CustomField>
    <fullName>Establish_Date__c</fullName>
    <label>Establish_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Basic_Salary__c.field-meta.xml
<CustomField>
    <fullName>Basic_Salary__c</fullName>
    <label>Basic_Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/DA__c.field-meta.xml
<CustomField>
    <fullName>DA__c</fullName>
    <label>DA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/HRA__c.field-meta.xml
<CustomField>
    <fullName>HRA__c</fullName>
    <label>HRA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/TA__c.field-meta.xml
<CustomField>
    <fullName>TA__c</fullName>
    <label>TA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/butttondisplaydataClass.cls
public with sharing class butttondisplaydataClass {
    @AuraEnabled(cacheable=true)
    public static List<Account> getAccountList() {
        return [SELECT Id, Name, Type, Industry, Phone FROM Account LIMIT 10];
    }
    @AuraEnabled(cacheable=true)
    public static List<Contact> getContactList() {
        return [SELECT Id, Name,Phone,Email FROM Contact LIMIT 10];
    }
    @AuraEnabled(cacheable=true)
    public static List<Opportunity> getOpportunityList() {
        return [SELECT Id, Name,StageName,CloseDate FROM Opportunity LIMIT 10];
    }
    @AuraEnabled(cacheable=true)
    public static List<Lead> getLeadList() {
        return [SELECT Id, Name,Email,Phone FROM Lead LIMIT 10];
    }
    @AuraEnabled(cacheable=true)
    public static List<Employee__c> getEmpList() {
        return [SELECT Id, Name,Basic_Salary__c,HRA__c,DA__c,TA__c  FROM Employee__c LIMIT 10];
    }
    @AuraEnabled(cacheable=true)
    public static List<Department__c> getDepList() {
        return [SELECT Id, Name,Establish_Date__c,Department_Location__c FROM Department__c LIMIT 10];
    }
}